### ISSUE TITLE
Coriolis NPC Generator for Foundry

### ISSUE THREAD

**Issue by coderunner** [rwinslow/rwinslow.github.io#3]
Hi Rich,

Weird use of github issues I know :) 

Thanks for https://rwinslow.github.io/, I use it to help me run my Coriolis games!!

I wanted to let you know that I created a Foundry VTT macro based on your NPC generator for Coriolis. Would you mind if I share it with more Coriolis fans?

https://github.com/coderunner/foundry-macros/blob/master/coriolis/generate-npc.js

**Comment by rwinslow** [comment]
Glad you’re getting use out of it! Yup, go for it.
